version: "3.9"

services:
  app:
    image: php:8.3-cli
    container_name: cinar_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  postgres:
    image: postgres:15
    container_name: cinar_postgres
    environment:
      POSTGRES_DB: cinar_siparis
      POSTGRES_USER: cinar_siparis_user
      POSTGRES_PASSWORD: cinar_siparis_pass
    ports:
      - "5432:5432"